version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: direct
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
